In [1]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from geopy.distance import geodesic

In [2]:
#reading in the csv file
staten_island_df = pd.read_csv("Resources/staten_island.csv")
staten_island_df.head()

   OBJECTID        Borough  Offense   Latitude  Longitude Public Area
0         1  Staten Island  ROBBERY  40.643566 -74.074001         NaN
1         2  Staten Island  ROBBERY  40.635961 -74.161365         NaN
2         3  Staten Island  ROBBERY  40.643569 -74.098338         NaN
3         4  Staten Island  ROBBERY  40.630408 -74.142977         NaN
4         5  Staten Island  ROBBERY  40.630539 -74.076641         NaN

In [3]:
# crimes df
crimes = staten_island_df.iloc[0:365, :]
offense_df = crimes.drop(columns= ["Borough", "Public Area"])
offense_df.head()

   OBJECTID  Offense   Latitude  Longitude
0         1  ROBBERY  40.643566 -74.074001
1         2  ROBBERY  40.635961 -74.161365
2         3  ROBBERY  40.643569 -74.098338
3         4  ROBBERY  40.630408 -74.142977
4         5  ROBBERY  40.630539 -74.076641

In [4]:
# public institutions df
public = staten_island_df.iloc[366:389, :]
public_area_df = public.drop(columns= ["Borough", "Offense"])
public_area_df.head()

     OBJECTID   Latitude  Longitude                      Public Area
366       367  40.614533 -74.074185                            PARKS
367       368  40.510392 -74.230405  RECREATION AND WATERFRONT SITES
368       369  40.595802 -74.063027                 PUBLIC LIBRARIES
369       370  40.590395 -74.101138                 PUBLIC LIBRARIES
370       371  40.638748 -74.083899                            PARKS

In [5]:
# offense coordinates (lat and lon)
for offense_index, offense_row in offense_df.iterrows():
    offense_lat = offense_row['Latitude']
    offense_lon = offense_row['Longitude']

    # public area coordinates (lat and lon)
    for public_index, public_row in public_area_df.iterrows():
        public_lat = public_row['Latitude']
        public_lon = public_row['Longitude']

        # Distance between offense and public area
        # Used Xpert Learning Assistant (via UNC Bootcamp site) to debug
        distance = geodesic((offense_lat, offense_lon), (public_lat, public_lon)).miles

        # Repeat
        # Used Xpert Learning Assistant (via UNC Bootcamp site) for code
        offense_df.loc[offense_index, f'Distance_to_Public_{public_index}'] = distance

# Print updated offense_df
offense_df

,OBJECTID,Offense,Latitude,Longitude,Distance_to_Public_366,Distance_to_Public_367,Distance_to_Public_368,Distance_to_Public_369,Distance_to_Public_370,Distance_to_Public_371,...,Distance_to_Public_379,Distance_to_Public_380,Distance_to_Public_381,Distance_to_Public_382,Distance_to_Public_383,Distance_to_Public_384,Distance_to_Public_385,Distance_to_Public_386,Distance_to_Public_387,Distance_to_Public_388
0,1,ROBBERY,40.643566,-74.074001,2.003356,12.334976,3.345906,3.936571,0.617397,4.570702,...,0.440115,9.820089,1.257431,12.869744,4.035769,10.025034,2.675753,7.817468,4.698597,2.521369
1,2,ROBBERY,40.635961,-74.161365,4.816013,9.395021,5.866473,4.462610,4.076523,0.062745,...,4.201471,7.228525,3.701164,9.749693,3.480541,7.726574,4.828698,6.156851,3.477882,2.362589
2,3,ROBBERY,40.643569,-74.098338,2.372017,11.520526,3.782928,3.672023,0.828653,3.301456,...,0.890131,9.056342,0.946670,12.014788,3.428575,9.338099,2.850061,7.230371,4.004691,1.461109
3,4,ROBBERY,40.630408,-74.142977,3.779083,9.473125,4.834892,3.530344,3.158422,1.012981,...,3.303416,7.154705,2.718745,9.893440,2.626441,7.572212,3.793240,5.771766,2.779712,1.343835
4,5,ROBBERY,40.630539,-74.076641,1.111976,11.583865,2.501522,3.054880,0.682933,4.426320,...,0.775455,9.052212,0.769317,12.139188,3.260117,9.222801,1.768262,6.987977,3.946128,2.157205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,361,ROBBERY,40.635738,-74.132124,3.379306,10.076930,4.560046,3.527554,2.543440,1.491176,...,2.675142,7.717483,2.173102,10.514326,2.772077,8.102351,3.507359,6.207727,3.076432,0.922177
361,362,ROBBERY,40.576854,-74.117437,3.454662,7.509365,3.146706,1.268127,4.620595,4.700670,...,4.813970,4.963218,3.978470,8.126274,1.372935,5.021047,2.801658,2.739366,1.219827,3.548395
362,363,ROBBERY,40.632740,-74.152082,4.283840,9.394267,5.331474,3.964032,3.608008,0.513893,...,3.743289,7.145041,3.199460,9.783683,3.011036,7.603256,4.292776,5.914016,3.074661,1.840332
363,364,ROBBERY,40.614616,-74.084716,0.553786,10.511678,1.728109,1.881254,1.665688,4.260952,...,1.833573,7.968547,1.178603,11.087328,2.224976,8.104127,0.729495,5.848249,2.925712,1.967802
364,365,ROBBERY,40.613121,-74.121981,2.515160,9.099447,3.322772,1.913265,2.671204,2.590658,...,2.864473,6.619423,2.030211,9.612148,1.140913,6.897977,2.328102,4.822513,1.588761,1.071363

In [8]:
# put public areas in a list
offense_df.columns.tolist()[4:]
public_places = offense_df.columns.tolist()[4:]

# locate offenses within 1-mile radius of public area
# Assistance from Justin Moore (tutor) in setting up for loop
filtered_data = []
for place in public_places:
    temp_df = offense_df.loc[offense_df[place] <= 1]
    filtered_data.append(temp_df)

# add all filtered data into df
# Assistance from Justin Moore (tutor) in creating code for filtered_offense_df
filtered_offense_df = pd.concat(filtered_data, ignore_index=True).drop_duplicates("OBJECTID")
filtered_offense_df

,OBJECTID,Offense,Latitude,Longitude,Distance_to_Public_366,Distance_to_Public_367,Distance_to_Public_368,Distance_to_Public_369,Distance_to_Public_370,Distance_to_Public_371,...,Distance_to_Public_379,Distance_to_Public_380,Distance_to_Public_381,Distance_to_Public_382,Distance_to_Public_383,Distance_to_Public_384,Distance_to_Public_385,Distance_to_Public_386,Distance_to_Public_387,Distance_to_Public_388
0,12,ROBBERY,40.627054,-74.077144,0.877880,11.394405,2.280631,2.826758,0.881573,4.429303,...,0.997952,8.858704,0.789583,11.955765,3.072916,9.018359,1.526553,6.775744,3.764663,2.126855
1,18,ROBBERY,40.606321,-74.065039,0.743208,10.933861,0.733502,2.193741,2.447371,5.434195,...,2.554389,8.388203,2.188601,11.550309,2.959293,8.423615,0.741010,6.129601,3.626498,3.150275
2,19,ROBBERY,40.608453,-74.082436,0.603527,10.315980,1.343137,1.587489,2.091802,4.538205,...,2.252357,7.767776,1.620359,10.907633,2.129761,7.868067,0.299732,5.592747,2.821982,2.298635
3,36,ROBBERY,40.613717,-74.084818,0.561950,10.465445,1.685655,1.823840,1.727842,4.278431,...,1.895836,7.921563,1.236581,11.042827,2.186536,8.053638,0.675822,5.795655,2.887352,1.993640
4,43,ROBBERY,40.612118,-74.070003,0.275890,10.978151,1.184100,2.219943,1.977401,5.046596,...,2.091876,8.429225,1.714214,11.577988,2.830633,8.505949,0.683809,6.219906,3.521721,2.738229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
659,311,ROBBERY,40.553185,-74.158714,6.139427,4.792115,5.830365,3.971067,7.095135,5.753943,...,7.293222,2.245848,6.432776,5.411475,3.630347,2.360609,5.509135,0.559314,2.997201,5.615418
674,62,ROBBERY,40.624951,-74.135996,3.328495,9.336054,4.332337,3.007591,2.899444,1.515768,...,3.062914,6.957195,2.387766,9.787107,2.128160,7.333666,3.297818,5.440424,2.346014,0.995671
681,225,ROBBERY,40.625526,-74.135102,3.291518,9.394685,4.309481,3.011014,2.842101,1.535798,...,3.004763,7.013359,2.334793,9.846733,2.146614,7.387389,3.272156,5.486968,2.380792,0.941192
685,246,ROBBERY,40.623933,-74.123371,2.666255,9.648754,3.719877,2.592742,2.313167,2.136234,...,2.489193,7.208888,1.755988,10.132803,1.890524,7.528970,2.673929,5.512990,2.297223,0.427805
688,309,ROBBERY,40.618152,-74.105070,1.643068,9.939103,2.695704,1.926393,1.805114,3.177595,...,2.003075,7.428759,1.143153,10.473924,1.674293,7.654375,1.644126,5.488674,2.310172,0.959202