In [22]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from geopy.distance import geodesic

In [23]:
#reading in the csv file
staten_island_df = pd.read_csv("Resources/staten_island.csv")
staten_island_df.head()

   OBJECTID        Borough  Offense   Latitude  Longitude Public Area
0         1  Staten Island  ROBBERY  40.643566 -74.074001         NaN
1         2  Staten Island  ROBBERY  40.635961 -74.161365         NaN
2         3  Staten Island  ROBBERY  40.643569 -74.098338         NaN
3         4  Staten Island  ROBBERY  40.630408 -74.142977         NaN
4         5  Staten Island  ROBBERY  40.630539 -74.076641         NaN

In [24]:
# crimes df
crimes = staten_island_df.iloc[0:365, :]
offense_df = crimes.drop(columns= ["Borough", "Public Area"])
offense_df.head()

   OBJECTID  Offense   Latitude  Longitude
0         1  ROBBERY  40.643566 -74.074001
1         2  ROBBERY  40.635961 -74.161365
2         3  ROBBERY  40.643569 -74.098338
3         4  ROBBERY  40.630408 -74.142977
4         5  ROBBERY  40.630539 -74.076641

In [25]:
# public institutions df
public = staten_island_df.iloc[366:389, :]
public_area_df = public.drop(columns= ["Borough", "Offense"])
public_area_df.head()

     OBJECTID   Latitude  Longitude                      Public Area
366       367  40.614533 -74.074185                            PARKS
367       368  40.510392 -74.230405  RECREATION AND WATERFRONT SITES
368       369  40.595802 -74.063027                 PUBLIC LIBRARIES
369       370  40.590395 -74.101138                 PUBLIC LIBRARIES
370       371  40.638748 -74.083899                            PARKS

In [29]:
# offense coordinates (lat and lon)
for offense_index, offense_row in offense_df.iterrows():
    offense_lat = offense_row['Latitude']
    offense_lon = offense_row['Longitude']

    # public area coordinates (lat and lon)
    for public_index, public_row in public_area_df.iterrows():
        public_lat = public_row['Latitude']
        public_lon = public_row['Longitude']

        # Distance between offense and public area
        # Used Xpert Learning Assistant (via UNC Bootcamp site) to debug
        distance = geodesic((offense_lat, offense_lon), (public_lat, public_lon)).miles

        # Repeat
        # Used Xpert Learning Assistant (via UNC Bootcamp site) for code
        offense_df.loc[offense_index, f'Distance_to_Public_{public_index}'] = distance

# Print updated offense_df
offense_df

,OBJECTID,Offense,Latitude,Longitude,Distance_to_Public_388,Distance_to_Public_366,Distance_to_Public_367,Distance_to_Public_368,Distance_to_Public_369,Distance_to_Public_370,...,Distance_to_Public_378,Distance_to_Public_379,Distance_to_Public_380,Distance_to_Public_381,Distance_to_Public_382,Distance_to_Public_383,Distance_to_Public_384,Distance_to_Public_385,Distance_to_Public_386,Distance_to_Public_387
0,1,ROBBERY,40.643566,-74.074001,2.521369,2.003356,12.334976,3.345906,3.936571,0.617397,...,0.307051,0.440115,9.820089,1.257431,12.869744,4.035769,10.025034,2.675753,7.817468,4.698597
1,2,ROBBERY,40.635961,-74.161365,2.362589,4.816013,9.395021,5.866473,4.462610,4.076523,...,4.317060,4.201471,7.228525,3.701164,9.749693,3.480541,7.726574,4.828698,6.156851,3.477882
2,3,ROBBERY,40.643569,-74.098338,1.461109,2.372017,11.520526,3.782928,3.672023,0.828653,...,0.972097,0.890131,9.056342,0.946670,12.014788,3.428575,9.338099,2.850061,7.230371,4.004691
3,4,ROBBERY,40.630408,-74.142977,1.343835,3.779083,9.473125,4.834892,3.530344,3.158422,...,3.440642,3.303416,7.154705,2.718745,9.893440,2.626441,7.572212,3.793240,5.771766,2.779712
4,5,ROBBERY,40.630539,-74.076641,2.157205,1.111976,11.583865,2.501522,3.054880,0.682933,...,0.914683,0.775455,9.052212,0.769317,12.139188,3.260117,9.222801,1.768262,6.987977,3.946128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,361,ROBBERY,40.635738,-74.132124,0.922177,3.379306,10.076930,4.560046,3.527554,2.543440,...,2.800659,2.675142,7.717483,2.173102,10.514326,2.772077,8.102351,3.507359,6.207727,3.076432
361,362,ROBBERY,40.576854,-74.117437,3.548395,3.454662,7.509365,3.146706,1.268127,4.620595,...,5.009922,4.813970,4.963218,3.978470,8.126274,1.372935,5.021047,2.801658,2.739366,1.219827
362,363,ROBBERY,40.632740,-74.152082,1.840332,4.283840,9.394267,5.331474,3.964032,3.608008,...,3.869993,3.743289,7.145041,3.199460,9.783683,3.011036,7.603256,4.292776,5.914016,3.074661
363,364,ROBBERY,40.614616,-74.084716,1.967802,0.553786,10.511678,1.728109,1.881254,1.665688,...,2.014129,1.833573,7.968547,1.178603,11.087328,2.224976,8.104127,0.729495,5.848249,2.925712
364,365,ROBBERY,40.613121,-74.121981,1.071363,2.515160,9.099447,3.322772,1.913265,2.671204,...,3.053083,2.864473,6.619423,2.030211,9.612148,1.140913,6.897977,2.328102,4.822513,1.588761

In [36]:
# offenses within 1-mile radius of public area
# Assistance from Justin Moore in setting up for loop and concat_df
offense_df.columns.tolist()[4:]
public_places = offense_df.columns.tolist()[4:]
filtered_data = []
for place in public_places:
    temp_df = offense_df.loc[offense_df[place] <= 1]
    filtered_data.append(temp_df)

concat_df = pd.concat(filtered_data, ignore_index=True).drop_duplicates("OBJECTID")
concat_df

,OBJECTID,Offense,Latitude,Longitude,Distance_to_Public_388,Distance_to_Public_366,Distance_to_Public_367,Distance_to_Public_368,Distance_to_Public_369,Distance_to_Public_370,...,Distance_to_Public_378,Distance_to_Public_379,Distance_to_Public_380,Distance_to_Public_381,Distance_to_Public_382,Distance_to_Public_383,Distance_to_Public_384,Distance_to_Public_385,Distance_to_Public_386,Distance_to_Public_387
0,6,ROBBERY,40.637135,-74.123473,0.685392,3.024397,10.398807,4.270352,3.432297,2.083167,...,2.335875,2.211683,8.003394,1.746015,10.853997,2.798902,8.358282,3.222860,6.393281,3.197301
1,10,ROBBERY,40.633764,-74.127213,0.632709,3.087651,10.096876,4.272293,3.291671,2.302659,...,2.580216,2.444270,7.706814,1.899664,10.550358,2.588866,8.068217,3.219754,6.122779,2.946663
2,11,ROBBERY,40.636810,-74.118650,0.591377,2.797807,10.519669,4.069492,3.332436,1.831562,...,2.092426,1.963605,8.103239,1.495227,10.986390,2.770763,8.439263,3.027657,6.435527,3.216769
3,15,MURDER,40.633250,-74.120539,0.376880,2.758148,10.260660,3.977727,3.128078,1.963025,...,2.254523,2.111110,7.840310,1.547040,10.730631,2.524635,8.174551,2.927786,6.172230,2.956466
4,34,ROBBERY,40.634484,-74.118152,0.429238,2.690451,10.401885,3.940310,3.171014,1.824408,...,2.108968,1.968629,7.976165,1.434257,10.874537,2.611082,8.304454,2.894668,6.288513,3.065476
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
677,132,ROBBERY,40.544900,-74.161376,6.197610,6.642800,4.344944,6.254215,4.461073,7.651240,...,8.046316,7.849117,1.836411,6.989802,4.992875,4.186790,1.828374,5.996630,0.525168,3.568394
678,143,ROBBERY,40.551951,-74.150635,5.546528,5.901022,5.085324,5.513847,3.717440,6.941938,...,7.336735,7.139386,2.559819,6.282310,5.725715,3.484355,2.570758,5.251988,0.344935,2.894911
679,230,ROBBERY,40.549539,-74.150735,5.706388,6.027413,4.989028,5.611272,3.841548,7.088633,...,7.483240,7.285882,2.479138,6.429809,5.637958,3.634882,2.451278,5.372973,0.181876,3.052783
681,310,ROBBERY,40.557871,-74.155367,5.249317,5.789950,5.132104,5.518363,3.630019,6.728456,...,7.123443,6.926567,2.583196,6.065982,5.740243,3.264151,2.726285,5.166955,0.771202,2.629010
682,311,ROBBERY,40.553185,-74.158714,5.615418,6.139427,4.792115,5.830365,3.971067,7.095135,...,7.490159,7.293222,2.245848,6.432776,5.411475,3.630347,2.360609,5.509135,0.559314,2.997201